language: cpp
git:
  depth: 3
compiler:
- gcc
matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
    end: CROSS=mingw64
before_install: |-
  if [ "$CROSS" == "mingw64" ]
  then
    sudo add-apt-repository "deb http://en.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse" # We need an up-to-date MinGW
    sudo apt-get update -qq
    sudo apt-get install -qq xenial gcc-mingw-w64-i686 g++-mingw-w64-i686 mingw32-runtime
  else
    sudo apt-get update -qq
    sudo apt-get install -qq libgeotiff-dev
  fi
script: |- 
  if [ "$CROSS" == "mingw64" ]
  then
    autoreconf --force --install && ./configure --host=x86_64-w64-mingw32 && make
  else
    autoreconf --force --install && ./configure && make
  fi
