language: cpp
git:
  depth: 3
matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
    env: CROSS=mingw64
before_install: |-
  if [ "$CROSS" == "mingw64" ]
  then
    sudo apt-get update -qq
    sudo apt-get install -qq gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 mingw-w64-dev
  else
    sudo apt-get update -qq
    sudo apt-get install -qq libgeotiff-dev
  fi
script: |- 
  if [ "$CROSS" == "mingw64" ]
  then
    autoreconf --force --install && ./configure --host=x86_64-w64-mingw32 && make
  else
    autoreconf --force --install && ./configure && make
  fi
