language: cpp
git:
  depth: 3
matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
    env: CROSS=mingw64
before_install: |-
  if [ "$CROSS" == "mingw64" ]
  then
    sudo apt-get update -qq
    sudo apt-get install -qq gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 mingw-w64-dev
#    wget http://download.osgeo.org/proj/proj-4.9.3.tar.gz
#    tar zxf proj-4.9.3.tar.gz
#    cd proj-4.9.3
#    ./configure --host=x86_64-w64-mingw32
#    make
#    sudo make install
#    cd
    wget http://zlib.net/zlib-1.2.11.tar.gz
    tar zxf zlib-1.2.11.tar.gz
    cd zlib-1.2.11
    ./configure --host=x86_64-w64-mingw32
    make
    sudo make install
    cd
    wget http://download.osgeo.org/geotiff/libgeotiff/libgeotiff-1.4.2.tar.gz
    tar zxf libgeotiff-1.4.2.tar.gz
    cd libgeotiff-1.4.2
    ./configure --host=x86_64-w64-mingw32 --without-proj
    make
    sudo make install
    cd
  else
    sudo apt-get update -qq
    sudo apt-get install -qq libgeotiff-dev
  fi
script: |- 
  if [ "$CROSS" == "mingw64" ]
  then
    autoreconf --force --install && ./configure --host=x86_64-w64-mingw32 && make
  else
    autoreconf --force --install && ./configure && make
  fi
