language: cpp
git:
  depth: 3
matrix:
  include:
  - os: linux
    compiler: x86_64-w64-mingw32-gcc
    env: CROSS=mingw64 
    addons:
      apt:
        packages:
         - gcc-mingw-w64-x86-64
         - g++-mingw-w64-x86-64
         - binutils-mingw-w64-x86-64
         - mingw-w64-dev
         - zlib1g-dev
before_install: |-
  if [ "$CROSS" == "mingw64" ]
  then
    export CC=x86_64-w64-mingw32-gcc
    export CXX=x86_64-w64-mingw32-g++
    wget http://zlib.net/zlib-1.2.11.tar.gz
    tar zxf zlib-1.2.11.tar.gz
    cd zlib-1.2.11
    sed -e s/"PREFIX ="/"PREFIX = x86_64-w64-mingw32-"/ -i win32/Makefile.gcc
    make -f win32/Makefile.gcc
    sudo INCLUDE_PATH=/usr/local/include LIBRARY_PATH=/usr/x86_64-w64-mingw32/sys-root/mingw/lib BINARY_PATH=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/bin make -f win32/Makefile.gcc install
    cd
    wget http://dl.maptools.org/dl/libtiff/tiff-3.8.2.tar.gz
    tar zxf tiff-3.8.2.tar.gz
    cd tiff-3.8.2
    ./configure --host=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --enable-cxx --disable-shared --enable-static --with-zlib-include-dir=/usr/local/include --with-zlib-lib-dir=/usr/x86_64-w64-mingw32/sys-root/mingw/lib
    make
    sudo make install
    cd
    wget http://download.osgeo.org/geotiff/libgeotiff/libgeotiff-1.4.2.tar.gz
    tar zxf libgeotiff-1.4.2.tar.gz
    cd libgeotiff-1.4.2
    export CFLAGS="-I/usr/local/include"
    export LDFLAGS="-L/usr/x86_64-w64-mingw32/sys-root/mingw/lib"
    ./configure --host=x86_64-w64-mingw32 --without-proj --prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --with-libtiff=/usr/x86_64-w64-mingw32/sys-root/mingw --disable-shared --enable-static
    make
    sudo make install
    cd $TRAVIS_BUILD_DIR
  fi
script: |- 
  if [ "$CROSS" == "mingw64" ]
  then
    autoreconf --force --install && ./configure --host=x86_64-w64-mingw32 && make
  else
    autoreconf --force --install && ./configure && make
  fi
