language: cpp
git:
  depth: 3
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
         - libgeotiff-dev
  - os: linux
    compiler: clang
    addons:
      apt:
        packages:
         - libgeotiff-dev
  - os: linux
    compiler: x86_64-w64-mingw32-gcc
    env: CROSS=mingw64 PLATFORM="mingw32" ARCH="x86_64" BITSIZE=64 HOST="x86_64" CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc
    addons:
      apt:
        packages:
         - gcc-mingw-w64-x86-64
         - g++-mingw-w64-x86-64
         - binutils-mingw-w64-x86-64
         - mingw-w64-dev
before_install: |-
  if [ "$CROSS" == "mingw64" ]
  then
    wget http://zlib.net/zlib-1.2.11.tar.gz
    tar zxf zlib-1.2.11.tar.gz
    cd zlib-1.2.11
    BINARY_PATH=/usr/x86_64-w64-mingw32/bin INCLUDE_PATH=/usr/x86_64-w64-mingw32/include LIBRARY_PATH=/usr/x86_64-w64-mingw32/lib make -f win32/Makefile.gcc
    BINARY_PATH=/usr/x86_64-w64-mingw32/bin INCLUDE_PATH=/usr/x86_64-w64-mingw32/include LIBRARY_PATH=/usr/x86_64-w64-mingw32/lib sudo -E make -f win32/Makefile.gcc install
    cd
    wget http://download.osgeo.org/geotiff/libgeotiff/libgeotiff-1.4.2.tar.gz
    tar zxf libgeotiff-1.4.2.tar.gz
    cd libgeotiff-1.4.2
    ./configure --host=x86_64-w64-mingw32 --without-proj
    make
    sudo make install
    cd $TRAVIS_BUILD_DIR
  fi
script: |- 
  if [ "$CROSS" == "mingw64" ]
  then
    autoreconf --force --install && ./configure --host=x86_64-w64-mingw32 && make
  else
    autoreconf --force --install && ./configure && make
  fi
