name: CI

on:
  push:
    branches: [ v1.2.5 ]
  pull_request:
    branches: [ v1.2.5 ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgeotiff-dev build-essential autoconf automake libtool

      - name: Build
        run: |
          autoreconf --force --install
          ./configure
          make

      - name: Archive Linux build
        run: |
          mkdir -p shared
          cp bin/ef5 shared/ef5 || true
          tar -czf shared/ef5_linux.tar.gz -C shared ef5 || true 